import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // <-- CHANGED THIS IMPORT

export const exportProjectPdf = (project, boqItems, totalAmount) => {
    // Create a new PDF document in Landscape orientation
    const doc = new jsPDF('landscape');

    // --- REPORT HEADER ---
    doc.setFontSize(18);
    doc.setTextColor(11, 23, 45); // Dark Blue
    doc.text(`Project Estimate Report: ${project.name || 'Untitled Project'}`, 14, 22);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100); // Gray

    // Left Column details
    doc.text(`Project Code: ${project.code || 'N/A'}`, 14, 32);
    doc.text(`Client: ${project.clientName || 'N/A'}`, 14, 38);
    doc.text(`Region: ${project.region || 'Auto (Default)'}`, 14, 44);

    // Right Column details
    doc.text(`Status: ${project.status || 'Draft'}`, 120, 32);
    doc.text(`Project Lead: ${project.projectLead || 'N/A'}`, 120, 38);

    // Total Amount Highlight
    doc.setFontSize(12);
    doc.setTextColor(16, 185, 129); // Success Green
    doc.text(`Total Estimated Cost: Rs. ${totalAmount.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`, 200, 38);

    // --- BOQ TABLE ---
    const tableColumn = ["Sl No", "Item Code", "Description", "Unit", "Total Qty", "Rate (Rs)", "Amount (Rs)"];
    const tableRows = [];

    boqItems.forEach(item => {
        const rowData = [
            item.slNo,
            item.displayCode || '-',
            item.displayDesc || '-',
            item.displayUnit || '-',
            Number(item.computedQty || 0).toFixed(2),
            Number(item.rate || 0).toFixed(2),
            Number(item.amount || 0).toFixed(2)
        ];
        tableRows.push(rowData);
    });

    // --- CHANGED THIS FUNCTION CALL ---
    autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 55,
        theme: 'grid',
        headStyles: { fillColor: [13, 31, 60], textColor: [255, 255, 255], fontStyle: 'bold' },
        styles: { fontSize: 9, cellPadding: 4, textColor: [50, 50, 50] },
        alternateRowStyles: { fillColor: [245, 248, 250] },
        columnStyles: {
            0: { cellWidth: 15, halign: 'center' }, // Sl No
            1: { cellWidth: 30 }, // Code
            2: { cellWidth: 'auto' }, // Description takes remaining space
            3: { cellWidth: 20, halign: 'center' }, // Unit
            4: { cellWidth: 25, halign: 'right' }, // Qty
            5: { cellWidth: 30, halign: 'right' }, // Rate
            6: { cellWidth: 40, halign: 'right', fontStyle: 'bold' }, // Amount
        }
    });

    // --- FOOTER ---
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by OpenPrix Estimation System | Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);
    }

    // Save the PDF
    doc.save(`${project.code || 'Project'}_Estimate_Report.pdf`);
};